config/routes.rb
Caliban::Application.routes.draw do

  root 'global#index'

  resources :users, except: ["index", "new"]
  resources :contacts
  resources :pings
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :eid, presence: true, uniqueness: true
	validates :name, presence: true
	validates :email, uniqueness: true
	validates :phoneNumber, allow_nil: true, allow_blank: true, uniqueness: true
	
	has_many :contacts, dependent: :destroy
	has_many :pings, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @dbUser = User.where(:eid => params[:user][:eid], :email => params[:user][:email]).first
    if @dbUser.blank?
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render action: 'show', status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      @dbUser.update(user_params)
      session[:id] = @dbUser.id
      respond_to do |format|
        format.json {render json: {result: "success", payload: {id: @dbUser.id}}}
      end
      #redirect_to user_path(:id => @dbUser.id), status: :found
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if (session[:id] && (String(session[:id]) == params[:id]))
        @user = User.find(session[:id])
      else
        redirect_to root_path, status: :found
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:eid, :name, :phoneNumber, :email, :imageURL)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eid %><br>
    <%= f.text_field :eid %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Eid</th>
      <th>Name</th>
      <th>Phonenumber</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.eid %></td>
        <td><%= user.name %></td>
        <td><%= user.phoneNumber %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- container -->
<div class="container">
    <!--<div id="notice"><%= notice %></div>-->

    <!-- sidebar -->
    <div class="container-col sidebar">
        <!-- logo -->
        <div class="sidebar-row logo">
            Caliban
        </div><!-- /logo -->
        <!-- sidebar-user -->
        <div class="sidebar-row sidebar-user">
            <div class="sidebar-user-pic">
                <img src="<%= @user.imageURL %>" />
            </div>
            <div class="sidebar-user-info">
                <div class="sidebar-user-info-detail name"><%= @user.name %></div>
                <div class="sidebar-user-info-detail"><%= @user.phoneNumber %></div>
                <div class="sidebar-user-info-detail"><%= @user.email %></div>
            </div>
        </div><!-- /sidebar-user -->
        <!-- sidebar-btns -->
        <div class="sidebar-row sidebar-btns">
            <div class="sidebar-btn edit-btn">edit account</div>
            <div class="sidebar-btn logout-btn">logout</div>
        </div><!-- /sidebar-btns -->
        <!-- sidebar-track -->
        <div class="sidebar-row sidebar-track">
            <div class="track-row header">&mdash; keeping in touch with &mdash;</div>
            <div class="track-row fraction">
                <div class="track-numer">025</div>
                <div class="track-denom">147 contacts</div>
                <div class="track-slash">/</div>
            </div>
        </div><!-- /sidebar-track -->
    </div><!-- /sidebar -->

    <!-- content -->
    <div class="container-col content">
        <!-- pings -->
        <div class="content-col pings">
            <div class="content-col-head"><span class="fa-bell"></span></div>
            <div class="list-create pings-pad">
              <div class="create-btn pings-create-btn"><span class="fa-plus"></span>Create Ping</div>
            </div>
            <div class="list pings-list">
              <ul>
                <li>Call <b>Nora Tarano</b> on Mondays</li>
                <li>Email <b>Ana Murillo</b> daily</li>
                <li>Email <b>Pilar Olivar</b> monthly</li>
                <li>Call <b>Nora Tarano</b> on Mondays</li>
                <li>Email <b>Ana Murillo</b> daily</li>
                <li>Email <b>Pilar Olivar</b> monthly</li>
                <li>Call <b>Nora Tarano</b> on Mondays</li>
                <li>Email <b>Ana Murillo</b> daily</li>
                <li>Email <b>Pilar Olivar</b> monthly</li>
                <li>Call <b>Nora Tarano</b> on Mondays</li>
                <li>Email <b>Ana Murillo</b> daily</li>
                <li>Email <b>Pilar Olivar</b> monthly</li>
                <li>Call <b>Nora Tarano</b> on Mondays</li>
                <li>Email <b>Ana Murillo</b> daily</li>
                <li>Email <b>Pilar Olivar</b> monthly</li>
              </ul>
            </div>
        </div><!-- /pings -->

        <div class="content-col content-sep"></div>

        <!-- contacts -->
        <div class="content-col contacts">
            <div class="content-col-head"><span class="fa-users"></span></div>
            <div class="list-create contacts-pad">
              <div class="create-btn contacts-create-btn"><span class="fa-plus"></span>Create Contact</div>
            </div>
            <div class="list contacts-list">
              <ul>
                <li>Ana Tarano</li>
                <li>Juan Sebastian Angarita</li>
                <li>Nora Tarano</li>
                <li>Pilar Olivar</li>
                <li>Ana Murillo</li>
                <li>Simon Perez Gonzalez</li>
                <li>Marlene Campos</li>
              </ul>
            </div>
      </div><!-- /contacts -->
    </div><!-- /content -->

</div><!-- /container -->