config/routes.rb
Caliban::Application.routes.draw do

  root 'global#index'

  resources :users, except: ["index", "new"]
  resources :contacts
  resources :pings
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :user, presence: true, associated: true
  validates :pointer, presence: true
  
  before_destroy do |c| c.pings.each do |p| p.destroy end end
    
  belongs_to :user
  has_one :pointer, dependent: :destroy
  has_many :contactpings, dependent: :destroy
  has_many :pings, through: :contactpings
  
  accepts_nested_attributes_for :pointer, allow_destroy: true
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = @user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_pointer
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      if (session[:id])
        @contact = Contact.find(params[:id])
        redirect_to root_path, status: :found if @contact.user_id != @user.id
      else
        redirect_to root_path, status: :found
      end
    end

    def set_user
      if (session[:id])
        @user = User.find(session[:id])
      else
        redirect_to root_path, status: :found
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      if params[:contact][:pointer_attributes][:id]
        @p = Pointer.find(params[:contact][:pointer_attributes][:id])
        if !@p || String(@p.contact.user_id) != String(@user.id)
          redirect_to root_path, status: :forbidden
        end
      end
      
      params[:contact][:user_id] = @user.id
      params.require(:contact).permit(:name, :user_id, :pointer_attributes => [:type, :value, :id])
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <%= f.fields_for(:pointer) do |ff| %>
    <div class="field">
      <%= ff.label :type %><br>
      <%= ff.select(:type, Pointer.acceptableTypes) %>
    </div>  
    
    <div class="field">
       <%= ff.label :value %><br>
       <%= ff.text_field :value %>
     </div>  
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts for <%= @user.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.user_id %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @contact.user_id %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>