config/routes.rb
Caliban::Application.routes.draw do

  root 'global#index'

  resources :users, except: ["index", "new"]
  resources :contacts
  resources :pings
end

app/models/ping.rb
class Ping < ActiveRecord::Base
  self.inheritance_column = :_type_disabled

  @@acceptableFrequencies = ["daily", "weekly", "monthly", "yearly"]
  
  def self.acceptableFrequencies
    @@acceptableFrequencies
  end

  validates :frequency, presence: true, inclusion: {:in => @@acceptableFrequencies}  
  validates :type, presence: true, inclusion: {:in => Pointer.acceptableTypes}
  validates :user, presence: true, associated: true
  
  belongs_to :user
  has_one :contactping, dependent: :destroy
  has_one :contact, through: :contactping
  
  accepts_nested_attributes_for :contactping
end

app/controllers/pings_controller.rb
class PingsController < ApplicationController
  before_action :set_user
  before_action :set_ping, only: [:show, :edit, :update, :destroy]

  # GET /pings
  # GET /pings.json
  def index
    @pings = @user.pings
  end

  # GET /pings/1
  # GET /pings/1.json
  def show
  end

  # GET /pings/new
  def new
    @ping = Ping.new
    @ping.build_contactping
    @contacts = @user.contacts
  end

  # GET /pings/1/edit
  def edit
    @contacts = @user.contacts
  end

  # POST /pings
  # POST /pings.json
  def create
    @ping = Ping.new(ping_params)

    respond_to do |format|
      if @ping.save
        format.html { redirect_to @ping, notice: 'Ping was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ping }
      else
        format.html { render action: 'new' }
        format.json { render json: @ping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pings/1
  # PATCH/PUT /pings/1.json
  def update
    respond_to do |format|
      if @ping.update(ping_params)
        format.html { redirect_to @ping, notice: 'Ping was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pings/1
  # DELETE /pings/1.json
  def destroy
    @ping.destroy
    respond_to do |format|
      format.html { redirect_to pings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ping
      if (session[:id])
        @ping = Ping.find(params[:id])
        redirect_to root_path, status: :forbidden if @ping.user_id != @user.id
      else
        redirect_to root_path, status: :forbidden
      end
    end
    
    def set_user
      if (session[:id])
        @user = User.find(session[:id])
      else
        redirect_to root_path, status: :forbidden
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ping_params
      if params[:ping][:contactping_attributes][:id]
        @cp = Contactping.find(params[:ping][:contactping_attributes][:id])
        if !@cp || String(@cp.contact.user_id) != String(@user.id)
          redirect_to root_path, status: :forbidden
        end
      end
      
      params[:ping][:user_id] = @user.id
      params.require(:ping).permit(:frequency, :type, :user_id, contactping_attributes: [:contact_id, :id])
    end
    
end

app/helpers/pings_helper.rb
module PingsHelper
end

app/views/pings/_form.html.erb
<%= form_for(@ping) do |f| %>
  <% if @ping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ping.errors.count, "error") %> prohibited this ping from being saved:</h2>

      <ul>
      <% @ping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.select(:frequency, Ping.acceptableFrequencies) %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select(:type, Pointer.acceptableTypes) %>
  </div>
  
  <%= f.fields_for(:contactping) do |ff| %>
    <div class="field">
      <%= ff.label :contact_id %><br>
      <%= ff.collection_select(:contact_id, @contacts, :id, :name) %>
    </div>
  <%end%>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pings/edit.html.erb
<h1>Editing ping</h1>

<%= render 'form' %>

<%= link_to 'Show', @ping %> |
<%= link_to 'Back', pings_path %>

app/views/pings/index.html.erb
<h1>Listing pings for <%= @user.name %></h1>

<table>
  <thead>
    <tr>
      <th>Frequency</th>
      <th>Type</th>
      <th>Lastrun</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pings.each do |ping| %>
      <tr>
        <td><%= ping.frequency %></td>
        <td><%= ping.type %></td>
        <td><%= ping.lastRun %></td>
        <td><%= ping.user_id %></td>
        <td><%= link_to 'Show', ping %></td>
        <td><%= link_to 'Edit', edit_ping_path(ping) %></td>
        <td><%= link_to 'Destroy', ping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ping', new_ping_path %>

app/views/pings/new.html.erb
<h1>New ping</h1>

<%= render 'form' %>

<%= link_to 'Back', pings_path %>

app/views/pings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frequency:</strong>
  <%= @ping.frequency %>
</p>

<p>
  <strong>Type:</strong>
  <%= @ping.type %>
</p>

<p>
  <strong>Lastrun:</strong>
  <%= @ping.lastRun %>
</p>

<p>
  <strong>User:</strong>
  <%= @ping.user_id %>
</p>

<%= link_to 'Edit', edit_ping_path(@ping) %> |
<%= link_to 'Back', pings_path %>